### ISSUE TITLE
☂️ General accessibility checklist (excluding board interaction)

### ISSUE THREAD

**Issue by veloce** [lichess-org/mobile#467]
We should ensure the application is accessible, using the [flutter checklist](https://docs.flutter.dev/ui/accessibility-and-internationalization/accessibility#accessibility-release-checklist).

## Active interactions

- [ ] Play tab
- [ ] create game screen
- [ ] create custom game screen
- [ ] create correspondence game screen
- [ ] user profile screen
- [ ] puzzle tab
- [ ] puzzle screen
- [ ] puzzle theme screen
- [ ] puzzle storm screen
- [ ] analysis screen
- [ ] friends popup screen
- [ ] watch tab
- [ ] tv screen
- [ ] streamers screen
- [ ] settings screen

## Screen reader testing

- [ ] Play tab
- [ ] create game screen
- [ ] create custom game screen
- [ ] create correspondence game screen
- [ ] user profile screen
- [ ] puzzle tab
- [ ] puzzle screen
- [ ] puzzle theme screen
- [ ] puzzle storm screen
- [ ] analysis screen
- [ ] friends popup screen
- [ ] watch tab
- [ ] tv screen
- [ ] streamers screen
- [ ] settings screen

## Contrast ratios

- [ ] Play tab
- [ ] create game screen
- [ ] create custom game screen
- [ ] create correspondence game screen
- [ ] user profile screen
- [ ] puzzle tab
- [ ] puzzle screen
- [ ] puzzle theme screen
- [ ] puzzle storm screen
- [ ] analysis screen
- [ ] friends popup screen
- [ ] watch tab
- [ ] tv screen
- [ ] streamers screen
- [ ] settings screen

## Tappable targets

- [ ] Play tab
- [ ] create game screen
- [ ] create custom game screen
- [ ] create correspondence game screen
- [ ] user profile screen
- [ ] puzzle tab
- [ ] puzzle screen
- [ ] puzzle theme screen
- [ ] puzzle storm screen
- [ ] analysis screen
- [ ] friends popup screen
- [ ] watch tab
- [ ] tv screen
- [ ] streamers screen
- [ ] settings screen

## Color vision deficiency testing

- [ ] Play tab
- [ ] create game screen
- [ ] create custom game screen
- [ ] create correspondence game screen
- [ ] user profile screen
- [ ] puzzle tab
- [ ] puzzle screen
- [ ] puzzle theme screen
- [ ] puzzle storm screen
- [ ] analysis screen
- [ ] friends popup screen
- [ ] watch tab
- [ ] tv screen
- [ ] streamers screen
- [ ] settings screen

## Scale factors

- [ ] Play tab
- [ ] create game screen
- [ ] create custom game screen
- [ ] create correspondence game screen
- [ ] user profile screen
- [ ] puzzle tab
- [ ] puzzle screen
- [ ] puzzle theme screen
- [ ] puzzle storm screen
- [ ] analysis screen
- [ ] friends popup screen
- [ ] watch tab
- [ ] tv screen
- [ ] streamers screen
- [ ] settings screen

**Comment by Boubou78000** [comment]
@veloce maybe review the checklist again
